
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Controllers.ProductoController;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author santi
 */
public class CrearProducto extends javax.swing.JFrame {

    int idCategoriaV, stockV;
    String nombreV, descripcionV, referenciaV;
    float precioV;
    
    ProductoController productoController;
    
    /**
     * Creates new form CrearProducto
     */
    public CrearProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        productoController = new ProductoController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_crearProducto = new javax.swing.JLabel();
        txt_referenciaProd = new javax.swing.JTextField();
        txt_nombreProd = new javax.swing.JTextField();
        txt_descripcionProd = new javax.swing.JTextField();
        txt_categoriaProd = new javax.swing.JTextField();
        txt_stockProd = new javax.swing.JTextField();
        txt_precioProd = new javax.swing.JTextField();
        lbl_referencia = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_categoria = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        btn_crearProd = new javax.swing.JButton();
        btn_atrasProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_crearProducto.setText("Crear Producto");

        txt_stockProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockProdActionPerformed(evt);
            }
        });

        lbl_referencia.setText("Referencia");

        lbl_nombre.setText("Nombre");

        lbl_descripcion.setText("Descripcion");

        lbl_categoria.setText("Categoria");

        lbl_stock.setText("Stock");

        lbl_precio.setText("Precio");

        btn_crearProd.setText("Crear");
        btn_crearProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearProdActionPerformed(evt);
            }
        });

        btn_atrasProd.setText("Atras");
        btn_atrasProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_atrasProd)
                        .addGap(18, 18, 18)
                        .addComponent(btn_crearProd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_referencia)
                                .addComponent(lbl_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_referenciaProd)
                            .addComponent(txt_nombreProd)
                            .addComponent(txt_descripcionProd)
                            .addComponent(txt_categoriaProd)
                            .addComponent(txt_stockProd)
                            .addComponent(txt_precioProd, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lbl_crearProducto)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_crearProducto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_referencia)
                    .addComponent(txt_referenciaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_descripcionProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_categoriaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_categoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stockProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_stock))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_precioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crearProd)
                    .addComponent(btn_atrasProd))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_stockProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockProdActionPerformed

    private void btn_crearProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearProdActionPerformed
        nombreV = txt_nombreProd.getText();
        descripcionV = txt_descripcionProd.getText();
        referenciaV = txt_referenciaProd.getText();



        try {
            // Convertir el texto a un número entero
            idCategoriaV = Integer.parseInt(txt_categoriaProd.getText());
        } catch (NumberFormatException e) {
            // Manejar el caso en que el texto no sea un número válido
            JOptionPane.showMessageDialog(null, "Por favor, ingresa una categoria que sea válida");
        }
        
        try {
            // Convertir el texto a un número entero
            stockV = Integer.parseInt(txt_stockProd.getText());
        } catch (NumberFormatException e) {
            // Manejar el caso en que el texto no sea un número válido
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un stock que sea válido");
        }
        
        try {
            // Convertir el texto a un número entero
            precioV = Float.parseFloat(txt_precioProd.getText());
        } catch (NumberFormatException e) {
            // Manejar el caso en que el texto no sea un número válido
            JOptionPane.showMessageDialog(null, "Por favor, ingresa un precio que sea válido");
        }
        
        
        
        try {
            productoController.crearProducto(idCategoriaV, referenciaV, nombreV, descripcionV, stockV, precioV);
            JOptionPane.showMessageDialog(null, "Datos registrados exitosamente");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar el registro en la base de datos"+ e.getMessage());
        }
                                
    }//GEN-LAST:event_btn_crearProdActionPerformed

    private void btn_atrasProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atrasProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atrasProd;
    private javax.swing.JButton btn_crearProd;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_crearProducto;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_referencia;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JTextField txt_categoriaProd;
    private javax.swing.JTextField txt_descripcionProd;
    private javax.swing.JTextField txt_nombreProd;
    private javax.swing.JTextField txt_precioProd;
    private javax.swing.JTextField txt_referenciaProd;
    private javax.swing.JTextField txt_stockProd;
    // End of variables declaration//GEN-END:variables
}
